name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make g++

      - name: Configure ${{ matrix.build_type }} build
        run: |
          cmake -S . -B build-${{ matrix.build_type }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: ${{ matrix.build_type }} build
        run: cmake --build build-${{ matrix.build_type }} -j$(nproc) -- all

      - name: Test ${{ matrix.build_type }} build
        run: ctest --test-dir build-${{ matrix.build_type }} --output-on-failure
